<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- General Dependencies -->
  <ItemGroup>
    <PackageVersion Include="Spectre.Console" Version="0.50.0" />
  </ItemGroup>

  <!-- Test-Only Dependencies -->
  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="NUnit" Version="4.2.2" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.4.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageVersion Include="Spectre.Console.Testing" Version="0.50.0" />
  </ItemGroup>
</Project>