<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
    <TargetFramework>$(CommonTargetFramework)</TargetFramework>
    <RootNamespace>Squire.NumTic.Benchmark</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
  </PropertyGroup>

   <ItemGroup>
     <None Remove="README.md" />
   </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Game\NumTic.Game.csproj" />
    <ProjectReference Include="..\src\Console\NumTic.Console.csproj" />
  </ItemGroup>
</Project>
