<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(CommonTargetFramework)</TargetFramework>
    <RootNamespace>Squire.NumTic.AI</RootNamespace>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
  </PropertyGroup>

   <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <!-- Package References -->
  <ItemGroup>
    <PackageReference Include="OpenAI" />
  </ItemGroup>

  <!-- Project References -->
  <ItemGroup>
    <ProjectReference Include="..\Game\NumTic.Game.csproj" />
  </ItemGroup>
</Project>
